version: '3.3'

services:
  virtual-lwm2m-client:
    image: virtual-lwm2m-client:develop
    volumes:
      - "./virtualDeviceLauncher/src/main/resources/devices.json:/opt/lwm2m-client/lib/devices.json"
    networks:
      - datamodel-net

networks:
  datamodel-net:
    external:
      name: datamodel-net